### PR TITLE
List dependencies

### PR DESCRIPTION
**Pull request by gleich**
Hello Nat! Thank you so much for everything you do as CEO! All of us in open-source really appreciate it :)

I added poetry config (like package.json but for python) to this project as well as a conventional requirements.txt so people can install all the dependencies with ease. Hope this helps!

### CODE REVIEW

**Comment by nat** [comment]
Thanks for this PR! I know it's good practice to have such dependency manifest files, and very much appreciate the contribution, but _personally_ I don't like having lots of files in my repos.

**Comment by safinsingh** [comment]
Just curious, why is that? I don't see the downside of locking dependency versions.

**Comment by nat** [comment]
It's a personal aesthetic – I'm a single-file kind of guy.

**Comment by safinsingh** [comment]
Ah okay, interesting approach. Thanks for sharing!

**Comment by gleich** [comment]
What about adding a command to install the deps in the README? It might be easier for people to get setup if they know what they need to install without reading the source code.

**Comment by nat** [comment]
Sounds good!

**Comment by gleich** [comment]
Looks like #6 (more specifically https://github.com/nat/ghtop/pull/6/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R10) has it covered. If that PR gets closed I will make a new one. Thank you for the quick responses, Nat!

**Comment by gleich** [comment]
@nat so I see that you have way more files now. Would you mind reconsidering this PR?

**Pull request closed without merging**
